# Tensors in PyTorch

Tensors are multi-way arrays that can represent inputs/outputs of a model as well as the model parameters. In PyTorch, tensors are very [similar](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label) to the `ndarrays` in NumPy, except that in PyTorch tensors have been [optimized](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html) to be able to run on hardware accelerators such as GPUs efficiently. Tensors in PyTorch can share the same underlying memory with NumPy arrays to avoid the computation costs for data copying. Tensors in PyTorch can also be optimized for automatic differentiation.

In [1]:
import torch
import numpy as np

## Tensor Initializations

In [2]:
# from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

display(x_data)

tensor([[1, 2],
        [3, 4]])

In [3]:
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

display(x_np)

tensor([[1, 2],
        [3, 4]])

In [4]:
# from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1672, 0.8985],
        [0.6966, 0.4052]]) 



In [5]:
# with random or constant values
# `shape` is a tuple representing tensor dimensions
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0703, 0.4300, 0.8271],
        [0.9282, 0.7773, 0.9787]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

Tensor operations can be run either on CPU or on hardware accelerators like GPU. By Default, tensors are created on the CPU, we can move the tensors from CPU to GPU using the `.to` method (when GPU is available), note that copying large tensors across devices can be expensive in terms of time and memory.

In [7]:
# check if GPU is available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [8]:
# numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')
tensor[:,1] = 0 # seting the second column to an all-zero vector
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
# arithmetic operations

# matrix multiplication
y1 = tensor @ tensor.T
print(f'y1: {y1}')

y2 = tensor.matmul(tensor.T)
print(f'y2: {y2}')

y3 = torch.rand_like(y1)
print(f'y3: {y3}')
torch.matmul(tensor, tensor.T, out=y3) # `out` for output tensor
print(f'y3: {y3}')

# hadamard product
z1 = tensor * tensor
print(f'z1: {z1}')
z2 = tensor.mul(tensor)
print(f'z2: {z2}')

z3 = torch.rand_like(tensor)
print(f'z3: {z3}')
torch.mul(tensor, tensor, out=z3)
print(f'z3: {z3}')

y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[0.9743, 0.6455, 0.0080, 0.3209],
        [0.8568, 0.5268, 0.5317, 0.9088],
        [0.2774, 0.4574, 0.3385, 0.6081],
        [0.6687, 0.1574, 0.3237, 0.2399]])
y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: tensor([[0.2524, 0.9753, 0.3246, 0.8861],
        [0.8590, 0.9456, 0.1139, 0.6801],
        [0.1142, 0.6856, 0.2706, 0.2219],
        [0.3993, 0.9063, 0.6309, 0.4979]])
z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
# single-element tensors can be created by aggregating the values of a tensor into one, and can be converted to a Python numerical value using `item()`
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [13]:
# in-place operations are denoted by a `_` suffix
print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**NOTE** In-place operations save memory but are usually discouraged in deep learning because they are not helpful during gradient computations due to immediate loss of history.